#local
spring:
  profiles:
    activate:
      on-profile: local

  # database
  datasource:
    url: jdbc:mysql://localhost:3306/testproj?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: ghtkssk10!
    driver-class-name: com.mysql.cj.jdbc.Driver

    # jpa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true

#encoding
server:
  servlet:
    encoding:
      charset: UTF-8